Fixed __eq__ function for BurrowState.  Created function to create a BurrowState of the complete puzzle.  This will replace calls to prior function detect_completion.  Removed references to ID.
A new problem has arised.  From error message the implementation of AStar appears to require that the object be hashable.  Apparently BurrowState cannot use lists, which are mutable.

This is the relevant information from the error ....
TypeError: unhashable type: 'BurrowState'